# double quotes as well as it's absence works
Dev:
  DeveloperKeys:
    consumer_key: "a123"
    consumer_secret: a123
    access_token: a123
    access_secret: a123
    bearer_token: a123
  Kafka:
    bootstrap_servers: ['localhost:9092']
    topic_name: TW_ANALYSIS
Prod:
  Description: "Prod Setup goes here"
